export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_ACCOUNTS = 'RECEIVE_ACCOUNTS'
export const SET_SHOW_VALUES = 'SET_SHOW_VALUES'
export const SET_SELECTED_ACCOUNT = 'SET_SELECTED_ACCOUNT'
export const SET_LOADING_DETAILS_ON = 'SET_LOADING_DETAILS_ON'
export const SET_LOADING_DETAILS_OFF = 'SET_LOADING_DETAILS_OFF'



export const SET_LOADING_ON = 'SET_LOADING_ON'
export const SET_LOADING_OFF = 'SET_LOADING_OFF'
export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'